"use client";

import "./globals.css";
import { SearchBarContextProvider } from "../context/SearchBarContext";
import Navigation from "@/components/Navigation/Navigation";

export const metadata = {
  title: "Marvel App",
  description: "Generated by Lucas Iannuzzi",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link
          href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css"
          rel="stylesheet"
          integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM"
          crossorigin="anonymous"
        />
        <link
          rel="stylesheet"
          href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css"
        />
      </head>
      <body>
        <SearchBarContextProvider>
          <Navigation />
          <div className="main-section">{children}</div>
          <script
            src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"
            integrity="sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz"
            crossorigin="anonymous"
          ></script>
        </SearchBarContextProvider>
      </body>
    </html>
  );
}
