import './globals.css'
import Navigation from '@/components/Navigation'

export const metadata = {
  title: 'Marvel App',
  description: 'Generated by Lucas Iannuzzi',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
      <Navigation/>
        {children}
        </body>
    </html>
  )
}
